#!/usr/bin/env bun
//
// Collapse `data/price-history/price-history.json` (~2.7 MB, time series) into
// `app/composables/data/prices.generated.ts` — a frozen lookup keyed by item
// slug holding only the latest record per item for the current league.
//
// Run automatically by `.github/workflows/collect-prices.yml` after the
// Python collector commits new daily snapshots. Run manually with
// `bun run build:prices` after editing price-history.json by hand.
//
// Why generate a TS module instead of fetching JSON at runtime:
//   - `public/` is gitignored in this repo, so we cannot ship a static JSON
//     file via Cloudflare Pages without checking it in to source.
//   - The module is tree-shakeable and bundled per-page by Nuxt — no extra
//     network hop, no hydration race.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { toItemSlug } from '../../../../../app/utils/itemSlug'

interface RawRecord {
  league: string
  item: string
  variant: string
  type: string
  date: string
  league_day: number
  price_chaos: number
  listings: number
  day_of_week: number
}

// File sits at .claude/skills/nuxt/scripts/build-prices/build.ts — 5 levels deep.
const REPO_ROOT = resolve(import.meta.dir, '../../../../..')
// `master.json` is the accumulated time series — collect.py merges each crawl
// into it, deduping by (league, item, variant, type, date). Per-day raw
// snapshots live under `data/price-history/daily/` for audit only.
const SOURCE = resolve(REPO_ROOT, 'data/price-history/master.json')
const NUXT_CONFIG = resolve(REPO_ROOT, 'nuxt.config.ts')
const OUTPUT = resolve(REPO_ROOT, 'app/composables/data/prices.generated.ts')

// Pull `currentLeague` from `nuxt.config.ts` (`runtimeConfig.public.currentLeague`)
// via regex so we never drift out of sync with the site config when league rolls.
function readCurrentLeague(): string {
  const cfg = readFileSync(NUXT_CONFIG, 'utf8')
  const m = cfg.match(/currentLeague:\s*['"]([^'"]+)['"]/)
  if (!m) throw new Error(`Cannot find currentLeague in ${NUXT_CONFIG}`)
  return m[1]!
}

function pickLatestPerItem(records: RawRecord[], league: string) {
  // For each item name, keep the record with max(date). Variants collapse —
  // see types/poe-item.ts header for why uniques (which would need variant
  // disambiguation) are out of scope for v1.
  const latest = new Map<string, RawRecord>()
  for (const r of records) {
    if (r.league !== league) continue
    const cur = latest.get(r.item)
    if (!cur || r.date > cur.date) latest.set(r.item, r)
  }
  return latest
}

function deriveDivineChaos(latest: Map<string, RawRecord>): number {
  const div = latest.get('Divine Orb')
  if (!div) {
    console.warn(`⚠️  No Divine Orb record found — divine conversion will be disabled`)
    return 0
  }
  return div.price_chaos
}

function emit(league: string, latest: Map<string, RawRecord>, divine: number): string {
  // Sort by slug so git diffs stay stable across rebuilds.
  const entries = [...latest.entries()]
    .map(([name, r]) => [
      toItemSlug(name),
      { name, type: r.type, price_chaos: r.price_chaos, listings: r.listings, as_of: r.date },
    ] as const)
    .sort(([a], [b]) => a.localeCompare(b))

  // One item per line — `JSON.stringify` per record handles every escape case
  // (quotes, backslashes, control chars) in item names safely while keeping
  // git diffs readable (each price change is exactly one line of churn).
  const itemLines = entries
    .map(([slug, entry]) => `    ${JSON.stringify(slug)}: ${JSON.stringify(entry)},`)
    .join('\n')

  return `// AUTO-GENERATED by .claude/skills/nuxt/scripts/build-prices/build.ts — do not edit.
// Run \`bun run build:prices\` to regenerate from data/price-history/price-history.json.

import type { PriceIndex } from '~/types/poe-item'

export const PRICES: PriceIndex = {
  league: ${JSON.stringify(league)},
  divine_chaos: ${divine},
  items: {
${itemLines}
  },
}
`
}

function main() {
  const league = readCurrentLeague()
  const raw = JSON.parse(readFileSync(SOURCE, 'utf8')) as RawRecord[]
  const latest = pickLatestPerItem(raw, league)
  const divine = deriveDivineChaos(latest)

  if (latest.size === 0) {
    throw new Error(`No records found for league "${league}" in ${SOURCE}. Check app.config.ts and run collect.py.`)
  }

  const out = emit(league, latest, divine)
  mkdirSync(dirname(OUTPUT), { recursive: true })
  writeFileSync(OUTPUT, out)
  console.log(`✓ ${OUTPUT}`)
  console.log(`  league=${league}  items=${latest.size}  divine=${divine}c`)
}

main()
