#!/usr/bin/env bun
//
// Collapse today's UTC snapshot in `data/price-history/daily/` into
// `app/composables/data/prices.generated.ts` — a frozen lookup keyed by item
// slug holding only fresh records for the configured current league.
//
// Run automatically by `.github/workflows/collect-prices.yml` after the
// Python collector writes a new daily snapshot. Run manually with
// `bun .claude/skills/nuxt/scripts/build-prices/build.ts` after collection.
//
// Why generate a TS module instead of fetching JSON at runtime:
//   - `public/` is gitignored in this repo, so we cannot ship a static JSON
//     file via Cloudflare Pages without checking it in to source.
//   - The module is tree-shakeable and bundled per-page by Nuxt — no extra
//     network hop, no hydration race.

import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { toItemSlug } from '../../../../../app/utils/itemSlug'

interface RawRecord {
  league: string
  item: string
  variant: string
  type: string
  date: string
  league_day: number
  price_chaos: number
  listings: number
  day_of_week: number
  price_unit: 'exalted'
}

// File sits at .claude/skills/nuxt/scripts/build-prices/build.ts — 5 levels deep.
const REPO_ROOT = resolve(import.meta.dir, '../../../../..')
// Historical master records must not let a failed or wrong-league crawl
// produce a successful build. Only today's daily snapshot can supply prices.
const DAILY_DIR = resolve(REPO_ROOT, 'data/price-history/daily')
const NUXT_CONFIG = resolve(REPO_ROOT, 'nuxt.config.ts')
const OUTPUT = resolve(REPO_ROOT, 'app/composables/data/prices.generated.ts')

// Pull `currentLeague` from `nuxt.config.ts` (`runtimeConfig.public.site.currentLeague`)
// via regex so we never drift out of sync with the site config when league rolls.
function readCurrentLeague(): string {
  const cfg = readFileSync(NUXT_CONFIG, 'utf8')
  const m = cfg.match(/currentLeague:\s*['"]([^'"]+)['"]/)
  if (!m) throw new Error(`Cannot find currentLeague in ${NUXT_CONFIG}`)
  return m[1]!
}

function readTodaySnapshot(league: string): RawRecord[] {
  const today = new Date().toISOString().slice(0, 10)
  const source = resolve(DAILY_DIR, `${today}.json`)
  if (!existsSync(source)) {
    throw new Error(`Missing today's UTC price snapshot: ${source}. Run collect.py before building prices.`)
  }

  const records = JSON.parse(readFileSync(source, 'utf8')) as RawRecord[]
  if (!Array.isArray(records) || records.length === 0) {
    throw new Error(`Empty or invalid price snapshot: ${source}`)
  }
  if (records.some(r => !r || r.league !== league || r.date !== today)) {
    throw new Error(`Price snapshot ${source} must contain only league "${league}" records dated ${today}. Check currentLeague in nuxt.config.ts and run collect.py.`)
  }
  if (records.some(r => r.price_unit !== 'exalted' || typeof r.item !== 'string' || !r.item.trim()
    || typeof r.type !== 'string' || !r.type.trim()
    || !Number.isFinite(r.price_chaos) || r.price_chaos <= 0
    || !Number.isFinite(r.listings) || r.listings < 0)) {
    throw new Error('Invalid price record: expected positive exalted prices and nonnegative quantities')
  }
  return records
}

function pickLatestPerItem(records: RawRecord[], league: string) {
  const latest = new Map<string, RawRecord>()
  for (const r of records) {
    if (r.league !== league) continue
    const cur = latest.get(r.item)
    if (!cur || r.date > cur.date) latest.set(r.item, r)
  }
  return latest
}

function deriveDivineChaos(latest: Map<string, RawRecord>): number {
  const div = latest.get('Divine Orb')
  if (!div) {
    throw new Error('Missing Divine Orb quote; refusing to disable currency conversion')
  }
  return div.price_chaos
}

function emit(league: string, latest: Map<string, RawRecord>, divine: number): string {
  // Sort by slug so git diffs stay stable across rebuilds.
  const entries = [...latest.entries()]
    .map(([name, r]) => [
      toItemSlug(name),
      { name, type: r.type, price_chaos: r.price_chaos, listings: r.listings, as_of: r.date },
    ] as const)
    .sort(([a], [b]) => a.localeCompare(b))

  if (new Set(entries.map(([slug]) => slug)).size !== entries.length) {
    throw new Error('Item slug collision; refusing to silently overwrite a price')
  }

  // One item per line — `JSON.stringify` per record handles every escape case
  // (quotes, backslashes, control chars) in item names safely while keeping
  // git diffs readable (each price change is exactly one line of churn).
  const itemLines = entries
    .map(([slug, entry]) => `    ${JSON.stringify(slug)}: ${JSON.stringify(entry)},`)
    .join('\n')

  return `// AUTO-GENERATED by .claude/skills/nuxt/scripts/build-prices/build.ts — do not edit.
// Run \`bun .claude/skills/nuxt/scripts/build-prices/build.ts\` after collecting today's prices.

import type { PriceIndex } from '~/types/poe-item'

export const PRICES: PriceIndex = {
  league: ${JSON.stringify(league)},
  divine_chaos: ${divine},
  items: {
${itemLines}
  },
}
`
}

function main() {
  const league = readCurrentLeague()
  const raw = readTodaySnapshot(league)
  const latest = pickLatestPerItem(raw, league)
  const divine = deriveDivineChaos(latest)

  if (latest.size === 0) {
    throw new Error(`No fresh records found for league "${league}". Check nuxt.config.ts and run collect.py.`)
  }

  const out = emit(league, latest, divine)
  mkdirSync(dirname(OUTPUT), { recursive: true })
  writeFileSync(OUTPUT, out)
  console.log(`✓ ${OUTPUT}`)
  console.log(`  league=${league}  items=${latest.size}  divine=${divine}ex`)
}

main()
