#!/usr/bin/env bun

/**
 * Build script for WikiLink data.
 * Scans content for :wiki-link{url="..."}, parses the local wiki mirror,
 * and generates wiki-links.generated.ts for the popover.
 */

import { Glob } from 'bun'
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { resolve, dirname } from 'node:path'

const CONTENT_DIR = resolve(process.cwd(), 'content')
const OUTPUT_FILE = resolve(process.cwd(), 'app/composables/data/wiki-links.generated.ts')

interface WikiItemData {
  name: string
  baseType?: string
  levelReq?: number
  implicits: string[]
  explicits: string[]
  flavour?: string
}

async function main() {
  console.log('🔍 Scanning for :wiki-link usages...')

  const files = await Array.fromAsync(new Glob('**/*.md').scan({ cwd: CONTENT_DIR, absolute: true }))

  const urls = new Set<string>()

  const regex = /:wiki-link\{[^}]*url=["']([^"']+)["'][^}]*\}/g

  for (const file of files) {
    const content = readFileSync(file, 'utf8')
    let match
    while ((match = regex.exec(content)) !== null) {
      urls.add(match[1])
    }
  }

  console.log(`   Found ${urls.size} unique wiki URLs.`)

  const data: Record<string, WikiItemData> = {}

  for (const url of urls) {
    // Convert URL to local mirror path (flat layout — no /wiki/ subfolder
    // since goscrape v0.5.0 + download.sh post-scrape flatten).
    // Example: https://www.poe2wiki.net/wiki/The_Hollow_Mask -> data/wiki/The_Hollow_Mask.md
    const match = url.match(/https:\/\/www\.(poe2?wiki\.net)\/wiki\/(.+)/)
    if (!match) {
      console.warn(`  ⚠️  Skipping invalid wiki URL: ${url}`)
      continue
    }

    // Workspace hosts one wiki (POE1 in poe1/, POE2 in poe2/) at data/wiki/.
    // Cross-game URLs (vd POE2 note referencing poewiki.net) skip with warning.
    // URL-encoded slugs (Xoph%27s_Pyre, The_M%C3%B3rrigan...) — filesystem
    // stores raw chars (Xoph's_Pyre, The_Mórrigan...) per MediaWiki convention.
    const page = decodeURIComponent(match[2])
    const localPath = resolve(process.cwd(), `data/wiki/${page}.md`)

    if (!existsSync(localPath)) {
      console.warn(`  ⚠️  Markdown not found for ${url} at ${localPath}`)
      continue
    }

    const content = readFileSync(localPath, 'utf8')
    const parsed = parseWikiMarkdown(content)

    if (parsed) {
      const key = page // use the page slug as key
      data[key] = parsed
      console.log(`  ✓ Parsed: ${parsed.name}`)
    }
  }

  // Generate the data file
  const output = `// AUTO-GENERATED by scripts/build-wiki-links
// Do not edit manually.

export interface WikiItemData {
  name: string
  baseType?: string
  levelReq?: number
  implicits: string[]
  explicits: string[]
  flavour?: string
}

export const ITEMS: Record<string, WikiItemData> = ${JSON.stringify(data, null, 2)} as const
`

  mkdirSync(dirname(OUTPUT_FILE), { recursive: true })
  writeFileSync(OUTPUT_FILE, output)

  console.log(`✅ Generated ${Object.keys(data).length} wiki items → ${OUTPUT_FILE}`)
}

function parseWikiMarkdown(content: string): WikiItemData | null {
  // Remove frontmatter
  const body = content.replace(/^---[\s\S]*?---\s*/, '')
  const lines = body.split('\n').map(l => l.trim()).filter(Boolean)

  const result: WikiItemData = {
    name: '',
    implicits: [],
    explicits: [],
  }

  // Simple heuristic parser for goscrape markdown
  for (let i = 0; i < Math.min(lines.length, 40); i++) {
    const line = lines[i]

    if (!result.name && /^[A-Z][A-Za-z\s\-']{3,50}$/.test(line)) {
      result.name = line
    }

    const req = line.match(/Requires Level\s*(\d+)/i)
    if (req) result.levelReq = parseInt(req[1])

    if (/^[\+\-–]/.test(line) || /^(Adds|Gain|You |While |When |If |% increased|% more|Chance to)/i.test(line)) {
      const cleaned = line.replace(/\*\*/g, '').replace(/\*([^*]+)\*/g, '$1').trim()
      if (cleaned.length > 4) {
        if (result.implicits.length < 2) {
          result.implicits.push(cleaned)
        } else {
          result.explicits.push(cleaned)
        }
      }
    }

    const flavour = line.match(/"([^"]{20,200}?)"\s*[\-\u2014]?/)
    if (flavour && !result.flavour) {
      result.flavour = flavour[1].replace(/\s+/g, ' ').trim()
    }
  }

  return result.name ? result : null
}

import { existsSync } from 'node:fs'

main().catch(console.error)
